export const EOI_MOCK = [
  {
    status: 'Draft',
    group_classification: 'Group 4',
    iosas_edu_yearname: '2025/26 SY',
    iosas_eionumber: 'EOI-01020',
    iosas_expressionofinterestid: null,
    iosas_authorityhead: {},
    iosas_authoritycontact: {},
    iosas_contact: {},
    iosas_edu_schoolauthority: null,
    iosas_edu_school: null,
    iosas_authorityaddressline1: null,
    iosas_authorityaddressline2: null,
    iosas_authoritycity: null,
    iosas_authoritycountry: null,
    iosas_authorityheadfirstname: null,
    iosas_authorityheadname: null,
    iosas_authorityheadyominame: null,
    iosas_authoritypostalcode: null,
    iosas_authorityprovince: null,
    iosas_authoritycontactname: null,
    iosas_authoritycontactyominame: null,
    iosas_contactname: null,
    iosas_contactyominame: null,
    iosas_designatedcontactfirstname: null,
    iosas_designatedcontactsameasauthorityhead: true,
    iosas_edu_schoolauthorityname: null,
    iosas_existingauthority: true,
    iosas_groupclassification: 'Group 4',
    iosas_proposedschoolname: 'Victoria South Elementary',
    iosas_schooladdressline1: null,
    iosas_schooladdressline2: null,
    iosas_schoolcity: null,
    iosas_schoolcountry: null,
    iosas_schoolpostalcode: null,
    iosas_schoolprovince: null,
    iosas_schoolauthoritycontactemail: null,
    iosas_schoolauthoritycontactname: null,
    ioas_schoolauthoritycontactphone: null,
    iosas_schoolauthorityheademail: null,
    iosas_schoolauthorityheadname: null,
    iosas_schoolauthorityheadphone: null,
    iosas_schoolauthorityname: null,
    iosas_seekgrouponeclassification: true,
    iosas_startgrade: null,
    iosas_endgrade: null,
    iosas_website: null,
  },
  {
    status: 'Approved',
    iosas_edu_yearname: '2024/25 SY',
    iosas_eionumber: 'EOI-01016',
    iosas_expressionofinterestid: null,
    iosas_authorityhead: {},
    iosas_authoritycontact: {},
    iosas_contact: {},
    iosas_edu_schoolauthority: null,
    iosas_edu_school: null,
    iosas_authorityaddressline1: null,
    iosas_authorityaddressline2: null,
    iosas_authoritycity: null,
    iosas_authoritycountry: null,
    iosas_authorityheadfirstname: null,
    iosas_authorityheadname: null,
    iosas_authorityheadyominame: null,
    iosas_authoritypostalcode: null,
    iosas_authorityprovince: null,
    iosas_authoritycontactname: null,
    iosas_authoritycontactyominame: null,
    iosas_contactname: null,
    iosas_contactyominame: null,
    iosas_designatedcontactfirstname: null,
    iosas_designatedcontactsameasauthorityhead: true,
    iosas_edu_schoolauthorityname: null,
    iosas_existingauthority: true,
    iosas_groupclassification: 'Group 3',
    iosas_proposedschoolname: 'Victoria South High',
    iosas_schooladdressline1: null,
    iosas_schooladdressline2: null,
    iosas_schoolcity: null,
    iosas_schoolcountry: null,
    iosas_schoolpostalcode: null,
    iosas_schoolprovince: null,
    iosas_schoolauthoritycontactemail: null,
    iosas_schoolauthoritycontactname: null,
    ioas_schoolauthoritycontactphone: null,
    iosas_schoolauthorityheademail: null,
    iosas_schoolauthorityheadname: null,
    iosas_schoolauthorityheadphone: null,
    iosas_schoolauthorityname: null,
    iosas_seekgrouponeclassification: true,
    iosas_startgrade: null,
    iosas_endgrade: null,
    iosas_website: null,
  },
  {
    status: 'Approved',
    iosas_edu_yearname: '2023/24 SY',
    iosas_eionumber: 'EOI-01003',
    iosas_expressionofinterestid: null,
    iosas_authorityhead: {},
    iosas_authoritycontact: {},
    iosas_contact: {},
    iosas_edu_schoolauthority: null,
    iosas_edu_school: null,
    iosas_authorityaddressline1: null,
    iosas_authorityaddressline2: null,
    iosas_authoritycity: null,
    iosas_authoritycountry: null,
    iosas_authorityheadfirstname: null,
    iosas_authorityheadname: null,
    iosas_authorityheadyominame: null,
    iosas_authoritypostalcode: null,
    iosas_authorityprovince: null,
    iosas_authoritycontactname: null,
    iosas_authoritycontactyominame: null,
    iosas_contactname: null,
    iosas_contactyominame: null,
    iosas_designatedcontactfirstname: null,
    iosas_designatedcontactsameasauthorityhead: true,
    iosas_edu_schoolauthorityname: null,
    iosas_existingauthority: true,
    iosas_groupclassification: 'Group 2',
    iosas_proposedschoolname: 'Victoria South Middle School',
    iosas_schooladdressline1: null,
    iosas_schooladdressline2: null,
    iosas_schoolcity: null,
    iosas_schoolcountry: null,
    iosas_schoolpostalcode: null,
    iosas_schoolprovince: null,
    iosas_schoolauthoritycontactemail: null,
    iosas_schoolauthoritycontactname: null,
    ioas_schoolauthoritycontactphone: null,
    iosas_schoolauthorityheademail: null,
    iosas_schoolauthorityheadname: null,
    iosas_schoolauthorityheadphone: null,
    iosas_schoolauthorityname: null,
    iosas_seekgrouponeclassification: true,
    iosas_startgrade: null,
    iosas_endgrade: null,
    iosas_website: null,
  },
];

export const SCHOOL_APPLICATION_MOCK = [
  {
    application_number: 'APP-1048',
    status: 'Draft',
    school_name: 'Victoria South High',
    school_year: '2024/25 SY',
    group_classification: 'Group 3',
    iosas_applicationid: null,
    iosas_edu_school: null,
    iosas_addressline1: null,
    iosas_addressline2: null,
    iosas_startgrade: null,
    iosas_endgrade: null,
    iosas_postalcode: null,
    iosas_province: null,
    iosas_phone: null,
    iosas_primaryschooltotal: true,
    iosas_privacypolicy: true,
    iosas_willhavecompletioncertificatepolicy: null,
    iosas_willsaoperateonnonprofitbasis: null,
  },
  {
    application_number: 'APP-1011',
    status: 'Interim Certification',
    school_name: 'Victoria South Middle School',
    school_year: '2023/24 SY',
    group_classification: 'Group 2',
    iosas_applicationid: null,
    iosas_edu_school: null,
    iosas_addressline1: null,
    iosas_addressline2: null,
    iosas_startgrade: null,
    iosas_endgrade: null,
    iosas_postalcode: null,
    iosas_province: null,
    iosas_phone: null,
    iosas_primaryschooltotal: true,
    iosas_privacypolicy: true,
    iosas_willhavecompletioncertificatepolicy: null,
    iosas_willsaoperateonnonprofitbasis: null,
  },
];
