export const EOI_MOCK = [
  {
    iosas_reviewstatus: 'Draft',
    _iosas_edu_year_value: '2025/26 SY',
    iosas_eionumber: 'EOI-01020',
    iosas_expressionofinterestid: null,
    iosas_authorityhead: {},
    iosas_authoritycontact: {},
    iosas_contact: {},
    iosas_edu_schoolauthority: null,
    iosas_edu_school: null,
    iosas_authorityaddressline1: '111 Douglas Street',
    iosas_authorityaddressline2: 'Unit 3, Upper level',
    iosas_authoritycity: 'Victoria',
    iosas_authoritycountry: 'Canada',
    iosas_authorityheadfirstname: 'Lisa',
    iosas_authorityheadname: 'Smith',
    iosas_authorityheadyominame: null,
    iosas_authoritypostalcode: 'V8V3Y2',
    iosas_authorityprovince: 'BC',
    iosas_authoritycontactname: null,
    iosas_authoritycontactyominame: null,
    iosas_contactname: null,
    iosas_contactyominame: null,
    iosas_designatedcontactfirstname: 'Jack',
    iosas_designatedcontactsameasauthorityhead: false,
    iosas_edu_schoolauthorityname: 'Victoria School Board',
    iosas_existingauthority: true,
    iosas_groupclassification: 'Group 4',
    iosas_proposedschoolname: 'Victoria South Elementary',
    iosas_schooladdressline1: null,
    iosas_schooladdressline2: null,
    iosas_schoolcity: null,
    iosas_schoolcountry: null,
    iosas_schoolpostalcode: null,
    iosas_schoolprovince: null,
    iosas_schoolauthoritycontactemail: 'jack.power@gmail.com',
    iosas_schoolauthoritycontactname: 'Power',
    ioas_schoolauthoritycontactphone: '(349) 049-4493',
    iosas_schoolauthorityheademail: 'lsmith@schools.bc.ca',
    iosas_schoolauthorityheadname: null,
    iosas_schoolauthorityheadphone: '(250) 193-5596',
    iosas_schoolauthorityname: null,
    iosas_seekgrouponeclassification: true,
    iosas_startgrade: 'Kindergarten',
    iosas_endgrade: '5',
    iosas_website: 'www.victoria-south-elementary.ca',
  },
  {
    iosas_reviewstatus: 'Approved',
    _iosas_edu_year_value: '2024/25 SY',
    iosas_eionumber: 'EOI-01016',
    iosas_expressionofinterestid: null,
    iosas_authorityhead: {},
    iosas_authoritycontact: {},
    iosas_contact: {},
    iosas_edu_schoolauthority: null,
    iosas_edu_school: null,
    iosas_authorityaddressline1: null,
    iosas_authorityaddressline2: null,
    iosas_authoritycity: null,
    iosas_authoritycountry: null,
    iosas_authorityheadfirstname: 'Jack',
    iosas_authorityheadname: 'Smith',
    iosas_authorityheadyominame: null,
    iosas_authoritypostalcode: null,
    iosas_authorityprovince: null,
    iosas_authoritycontactname: null,
    iosas_authoritycontactyominame: null,
    iosas_contactname: null,
    iosas_contactyominame: null,
    iosas_designatedcontactfirstname: null,
    iosas_designatedcontactsameasauthorityhead: true,
    iosas_edu_schoolauthorityname: null,
    iosas_existingauthority: true,
    iosas_groupclassification: 'Group 3',
    iosas_proposedschoolname: 'Victoria South High',
    iosas_schooladdressline1: null,
    iosas_schooladdressline2: null,
    iosas_schoolcity: null,
    iosas_schoolcountry: null,
    iosas_schoolpostalcode: null,
    iosas_schoolprovince: null,
    iosas_schoolauthoritycontactemail: null,
    iosas_schoolauthoritycontactname: null,
    ioas_schoolauthoritycontactphone: null,
    iosas_schoolauthorityheademail: null,
    iosas_schoolauthorityheadname: null,
    iosas_schoolauthorityheadphone: null,
    iosas_schoolauthorityname: null,
    iosas_seekgrouponeclassification: true,
    iosas_startgrade: null,
    iosas_endgrade: null,
    iosas_website: null,
  },
  {
    iosas_reviewstatus: 'Approved',
    _iosas_edu_year_value: '2023/24 SY',
    iosas_eionumber: 'EOI-01003',
    iosas_expressionofinterestid: null,
    iosas_authorityhead: {},
    iosas_authoritycontact: {},
    iosas_contact: {},
    iosas_edu_schoolauthority: null,
    iosas_edu_school: null,
    iosas_authorityaddressline1: null,
    iosas_authorityaddressline2: null,
    iosas_authoritycity: null,
    iosas_authoritycountry: null,
    iosas_authorityheadfirstname: 'Sam',
    iosas_authorityheadname: 'Smith',
    iosas_authorityheadyominame: null,
    iosas_authoritypostalcode: null,
    iosas_authorityprovince: null,
    iosas_authoritycontactname: null,
    iosas_authoritycontactyominame: null,
    iosas_contactname: null,
    iosas_contactyominame: null,
    iosas_designatedcontactfirstname: null,
    iosas_designatedcontactsameasauthorityhead: true,
    iosas_edu_schoolauthorityname: null,
    iosas_existingauthority: true,
    iosas_groupclassification: 'Group 2',
    iosas_proposedschoolname: 'Victoria South Middle School',
    iosas_schooladdressline1: null,
    iosas_schooladdressline2: null,
    iosas_schoolcity: null,
    iosas_schoolcountry: null,
    iosas_schoolpostalcode: null,
    iosas_schoolprovince: null,
    iosas_schoolauthoritycontactemail: null,
    iosas_schoolauthoritycontactname: null,
    ioas_schoolauthoritycontactphone: null,
    iosas_schoolauthorityheademail: null,
    iosas_schoolauthorityheadname: null,
    iosas_schoolauthorityheadphone: null,
    iosas_schoolauthorityname: null,
    iosas_seekgrouponeclassification: true,
    iosas_startgrade: null,
    iosas_endgrade: null,
    iosas_website: null,
  },
];

export const SCHOOL_APPLICATION_MOCK = [
  {
    iosas_applicationnumber: 'APP-1048',
    status: 'Draft',
    iosas_proposedschoolname: 'Victoria South High',
    iosas_studentshousedinadormitorysetting: true,
    iosas_confirmationofwatertesting: false,
    iosas_emergencydrillspolicyproceduresresponse: false,
    iosas_confirmationofleadtestingfordrinkingwater: false,
    iosas_proofofleasepurchaseoffacility: false,
    iosas_numberofstudentsg6: 0,
    iosas_applicationid: 'GUID',
    iosas_teacherandprincipalevaluationpolicy: false,
    _iosas_designatedcontact_value: 'GUID',
    _iosas_expressionofinterest_value: 'GUID',
    iosas_completedfreetuitionrefundpolicy: false,
    iosas_acknowledgementofinterviewdecisionsent: false,
    iosas_writtenconfirmationofeligibility: false,
    iosas_hasthesaobtainedirrevocableloc: false,
    iosas_primaryschooltotal: 0,
    iosas_hastheauthoritycontactedlocalgovernment: false,
    iosas_feerefundpolicyconsistentwithguidelines: false,
    iosas_proofoffacilityinspection: false,
    _modifiedby_value: 'GUID',
    iosas_willsaoperateonnonprofitbasis: false,
    iosas_municipalcomplianceletter: false,
    iosas_authorityheadlastname: 'Smith',
    iosas_businessplanincludingfinancialinformation: false,
    createdon: '2023-07-05T21:39:37Z',
    iosas_endgrade: 100000012,
    iosas_schoolclosurepolicy: false,
    statecode: 0,
    _owningbusinessunit_value: 'GUID',
    iosas_authorityheadphone: '250 415-5448',
    _owninguser_value: 'GUID',
    iosas_numberofstudentskindergarten: 0,
    iosas_familiarwithgrantstoispolicyifseekingfunds: false,
    iosas_proponentspreviouslyinvolvedinisbc: false,
    iosas_postalcode: 'V6X1N4',
    iosas_authorityprovince: 'BC',
    iosas_country: 'Canada',
    iosas_studentshousedinahomesetting: false,
    iosas_cantheauthorityconfirmtestingvspolicy: false,
    iosas_studentsupervisionpolicies: false,
    _createdby_value: 'GUID',
    iosas_policyincludessectionsdealingwithemergencies: false,
    iosas_authorityaddressline1: '10111 Bird Rd',
    _iosas_edu_schoolauthority_value: 'GUID',
    iosas_willhavecompletioncertificatepolicy: false,
    iosas_preexistingauthorityhead: true,
    iosas_authoritycomplieswithisaregulations: false,
    iosas_nopromotionofinappropriatedoctrines: false,
    iosas_numberofstudentsg5: 0,
    iosas_numberofstudentsg4: 0,
    iosas_numberofstudentsg7: 0,
    iosas_completesetofpoliciesoutlinedinchecklist: false,
    iosas_numberofstudentsg1: 0,
    iosas_numberofstudentsg2: 0,
    iosas_highschooltotal: 0,
    iosas_numberofstudentsg9: 0,
    iosas_numberofstudentsg8: 0,
    iosas_studentconductstandardsdisciplinepolicy: false,
    iosas_childabusepreventionpolicy: false,
    iosas_schoolauthority: '0532 Education Group Ltd.',
    _iosas_edu_year_value: '2024/25 SY',
    iosas_refundpolicyconsistentwiththeguidelines: false,
    versionnumber: 26877904,
    iosas_seekgroup1classification: false,
    iosas_authorityheadfirstname: 'Jack',
    iosas_policyincludepermanentschoolclosure: false,
    _iosas_schoolauthorityhead_value: 'GUID',
    iosas_studentrecordspolicy: false,
    iosas_numberofstudentsg3: 0,
    iosas_interviewpassedsuccessfully: false,
    iosas_appealsprocesspolicy: false,
    iosas_submissionmethod: 100000000,
    iosas_authoritycity: 'Richmond',
    iosas_educationalresourcepolicy: false,
    iosas_contactinformationfortwobusinessreferences: false,
    iosas_preexistingauthority: true,
    iosas_businessplansubmitted: false,
    iosas_approvedforinterimcertification: false,
    iosas_studentsafetypolicies: false,
    iosas_authoritycountry: 'CANADA',
    iosas_startgrade: 100000000,
    iosas_anaphylaxispolicyandprocedures: false,
    iosas_learningassistanceforspecialstudents: false,
    iosas_acknowledgementofreceiptsent: false,
    iosas_otheremergencydrillsimplemeneted: false,
    iosas_authoritypostalcode: 'V6X1N4',
    iosas_addressline1: '10111 Bird Rd',
    timezoneruleversionnumber: 0,
    iosas_acknowledgementofdecisionsent: false,
    statuscode: 100000003,
    iosas_numberofstudentsg11: 0,
    iosas_numberofstudentsg12: 0,
    iosas_reviewpassedsuccessfully: false,
    iosas_totalenrolment: 0,
    iosas_numberofstudentsg10: 0,
    iosas_province: 'BC',
    iosas_harassmentandbullyingpreventionpolicy: false,
    iosas_privacypolicy: false,
    iosas_policysubmitted: false,
    iosas_groupclassification: 'Group 3',
    iosas_city: 'Richmond',
    modifiedon: '2023-07-08T00:05:27Z',
    iosas_designatedcontactsameasauthorityhead: false,
    iosas_submissiondate: '2023-07-05T07:00:00Z',
    iosas_authorityheademail: 'jack.smith@gmail.com',
    iosas_willdevelopbudgetforexpenditurebasedoniep: false,
    iosas_irrevocableletterofcreditorsuretybond: false,
    iosas_name: 'SA-2024/25 SY-Demo 05-07-2023',
    iosas_willcomplywithenactmentsofbc: false,
    iosas_hassaobtaineddocumentsregardingbondingreqs: false,
    iosas_precertsubmissionreviewdate: null,
    iosas_testingdrinkingwaterforleadcontentpolicy: null,
    iosas_interimcertificationapprovaldate: null,
    iosas_reviewpanel: null,
    importsequencenumber: null,
    iosas_hastheauthoritydevelopedarefundpolicy: null,
    utcconversiontimezonecode: null,
    iosas_website: null,
    iosas_describefamiliaritywithbcscurriculum: null,
    overriddencreatedon: null,
    iosas_willapplyforstudentgraduationcreditpolicy: null,
    _iosas_interimcertificationapprover_value: null,
    iosas_interviewoutcomenotes: null,
    _iosas_interviewreviewer_value: null,
    iosas_howwillyouexercisegovernanceduties: null,
    iosas_specialeducationpolicy: null,
    iosas_grades112proposedhoursperday: null,
    iosas_interimcertificationreviewdate: null,
    iosas_decisionlettersentdate: null,
    iosas_ifnotoanyschoolpolicyexplainwhy: null,
    processid: null,
    _iosas_reviewer_value: null,
    traversedpath: null,
    _iosas_applicationsubmissionreviewer_value: null,
    iosas_proofoffacilityinspectionreceiveddate: null,
    iosas_authoritycode: null,
    iosas_applicationsubmissionreviewdate: null,
    iosas_schoolaffiliation: null,
    iosas_dateoflastannualreport: null,
    _owningteam_value: null,
    iosas_semestertype: null,
    _modifiedonbehalfby_value: null,
    iosas_schoolmincode: null,
    iosas_interviewscoring: null,
    iosas_graduationprogramcreditspolicyifapplicable: null,
    iosas_halfdaykindergartenproposedhoursperday: null,
    iosas_authoritywebsite: null,
    _createdonbehalfby_value: null,
    iosas_reviewstatus1: null,
    iosas_halfdaykindergartenproposedhoursperyear: null,
    iosas_reviewdate: null,
    iosas_notes: null,
    iosas_complywithhomestayguidelines: null,
    _iosas_edu_school_value: null,
    iosas_mailingaddresscity: null,
    iosas_fulldaykindergartenproposeddaysinsession: null,
    iosas_proofofleasereceiveddate: null,
    iosas_precertsubmissionapprovaldate: null,
    iosas_homeschoolingpolicyifapplicable: null,
    _iosas_precertsubmissionapprover_value: null,
    iosas_addressline2: null,
    iosas_interviewreviewnotes: null,
    iosas_interviewstatus1: null,
    iosas_authorityaddressline2: null,
    _iosas_interimcertificationreviewer_value: null,
    iosas_fulldaykindergartenproposedhoursperyear: null,
    iosas_mailingaddressprovince: null,
    iosas_interviewadditionalinformation: null,
    _iosas_applicationsubmissionapprover_value: null,
    iosas_numberofteachers: null,
    iosas_additionalprogramsother: null,
    _iosas_precertsubmissionreviewer_value: null,
    iosas_boardingsafetyandsupervisionpolicy: null,
    iosas_precertreviewnotes: null,
    iosas_reviewstatus: null,
    iosas_applicationsubmissionapprovaldate: null,
    iosas_grades112proposedhoursperyear: null,
    iosas_internationalstudentpoliciesifapplicable: null,
    iosas_interviewreviewdate: null,
    _iosas_approver_value: null,
    iosas_grades112proposeddaysinsession: null,
    iosas_detailsofinvolvement: null,
    iosas_phonenumber: null,
    iosas_officialregistrationnumber: null,
    iosas_precertificationstatus: null,
    iosas_mailingaddress2: null,
    iosas_mailingaddress1: null,
    _stageid_value: null,
    iosas_reviewnotes: null,
    iosas_nameofmunicipalityorregionaldistrict: null,
    iosas_approvaldate: null,
    iosas_additionalprograms: null,
    _iosas_interviewapprover_value: null,
    iosas_interviewapprovaldate: null,
    iosas_phone: null,
    iosas_schoolassociationother: null,
    iosas_mailingaddresscountry: null,
    iosas_halfdaykindergartenproposeddaysinsession: null,
    iosas_acknowledgementdate: null,
    iosas_incorporationtype: null,
    iosas_mailingaddresspostalcode: null,
    iosas_fulldaykindergartenproposedhoursperday: null,
    iosas_overview: null,
    iosas_awareoftherequirementsforcrchecks: false,
    iosas_awareofcertificationrequirements: null,
    iosas_whatstepsareyoutakingtoacquirethefacility: null,
  },
  {
    // General
    status: 'Interim Certification',
    iosas_applicationnumber: 'APP-1011',

    // MISSING - compliance booleans
    iosas_willcomplywithenactmentsofbc: false,

    // School Information - DONE - GET CONFIRMATION
    // MISSING - EMAIL
    iosas_proposedschoolname: 'iosas_proposedschoolname',
    iosas_startgrade: 'Kindergarten',
    iosas_endgrade: '6',
    iosas_overview: 'iosas_overview', // brief overview?
    iosas_addressline1: 'iosas_addressline1',
    iosas_addressline2: 'iosas_addressline2',
    iosas_postalcode: 'iosas_postalcode',
    iosas_country: 'iosas_country',
    iosas_province: 'iosas_province',
    iosas_city: 'iosas_city',
    iosas_mailingaddresscity: 'iosas_mailingaddresscity',
    iosas_mailingaddressprovince: 'iosas_mailingaddressprovince',
    iosas_mailingaddress2: 'iosas_mailingaddress2',
    iosas_mailingaddress1: 'iosas_mailingaddress1',
    iosas_mailingaddresscountry: 'iosas_mailingaddresscountry',
    iosas_mailingaddresspostalcode: 'iosas_mailingaddresspostalcode',
    iosas_website: 'iosas_website',
    iosas_phone: 'iosas_phone', // which one?
    iosas_phonenumber: 'iosas_phonenumber', // which one?
    iosas_groupclassification: 'Group 2',
    iosas_seekgroup1classification: false,
    iosas_schoolaffiliation: 'iosas_schoolaffiliation',

    // School Authority  - GET CONFIRMATION
    // MISSING - legislation checklist
    iosas_schoolauthority: 'iosas_schoolauthority',
    iosas_authorityheadphone: 'iosas_authorityheadphone',
    iosas_authorityheadfirstname: 'iosas_authorityheadfirstname',
    iosas_authorityheadlastname: 'iosas_authorityheadlastname',
    iosas_authorityaddressline1: 'iosas_authorityaddressline1',
    iosas_authorityheademail: 'iosas_authorityheademail',
    iosas_officialregistrationnumber: 'iosas_officialregistrationnumber',
    iosas_dateoflastannualreport: 'iosas_dateoflastannualreport',
    iosas_howwillyouexercisegovernanceduties:
      'iosas_howwillyouexercisegovernanceduties',
    iosas_proponentspreviouslyinvolvedinisbc: false, // Is this a boolean or string field? Is there a seperate string field?

    _iosas_edu_schoolauthority_value: 'GUID',
    iosas_preexistingauthorityhead: true,
    iosas_confirmationofwatertesting: false,
    iosas_proofofleasepurchaseoffacility: false,
    iosas_applicationid: 'GUID',
    _iosas_designatedcontact_value: 'GUID',
    _iosas_expressionofinterest_value: 'GUID',
    iosas_acknowledgementofinterviewdecisionsent: false,
    iosas_writtenconfirmationofeligibility: false,
    iosas_hasthesaobtainedirrevocableloc: false,
    iosas_proofoffacilityinspection: false,
    _modifiedby_value: 'GUID',
    iosas_municipalcomplianceletter: false,
    createdon: '2023-07-05T21:39:37Z',
    statecode: 0,
    _owningbusinessunit_value: 'GUID',
    _owninguser_value: 'GUID',
    iosas_authorityprovince: 'BC',
    _createdby_value: 'GUID',
    iosas_authoritycomplieswithisaregulations: false,
    iosas_nopromotionofinappropriatedoctrines: false,
    _iosas_edu_year_value: '2023/24 SY',
    versionnumber: 26877904,
    _iosas_schoolauthorityhead_value: 'GUID',
    iosas_interviewpassedsuccessfully: false,
    iosas_submissionmethod: 100000000,
    iosas_authoritycity: 'Richmond',
    iosas_contactinformationfortwobusinessreferences: false,
    iosas_preexistingauthority: true,
    iosas_businessplansubmitted: false,
    iosas_approvedforinterimcertification: false,
    iosas_studentsafetypolicies: false,
    iosas_authoritycountry: 'CANADA',
    iosas_acknowledgementofreceiptsent: false,
    iosas_authoritypostalcode: 'V6X1N4',
    timezoneruleversionnumber: 0,
    iosas_acknowledgementofdecisionsent: false,
    statuscode: 100000003,
    iosas_reviewpassedsuccessfully: false,
    modifiedon: '2023-07-08T00:05:27Z',
    iosas_designatedcontactsameasauthorityhead: false,
    iosas_submissiondate: '2023-07-05T07:00:00Z',
    iosas_irrevocableletterofcreditorsuretybond: false,
    iosas_name: 'SA-2024/25 SY-Demo 05-07-2023',
    iosas_hassaobtaineddocumentsregardingbondingreqs: false,
    iosas_precertsubmissionreviewdate: null,
    iosas_interimcertificationapprovaldate: null,
    iosas_reviewpanel: null,
    importsequencenumber: null,
    utcconversiontimezonecode: null,
    overriddencreatedon: null,
    _iosas_interimcertificationapprover_value: null,
    iosas_interviewoutcomenotes: null,
    _iosas_interviewreviewer_value: null,
    iosas_interimcertificationreviewdate: null,
    iosas_decisionlettersentdate: null,
    processid: null,
    _iosas_reviewer_value: null,
    traversedpath: null,
    _iosas_applicationsubmissionreviewer_value: null,
    iosas_proofoffacilityinspectionreceiveddate: null,
    iosas_authoritycode: null,
    iosas_applicationsubmissionreviewdate: null,
    _owningteam_value: null,
    iosas_semestertype: null,
    _modifiedonbehalfby_value: null,
    iosas_schoolmincode: null,
    iosas_interviewscoring: null,
    iosas_authoritywebsite: null,
    _createdonbehalfby_value: null,
    iosas_reviewstatus1: null,
    iosas_reviewdate: null,
    iosas_notes: null,
    _iosas_edu_school_value: null,
    iosas_proofofleasereceiveddate: null,
    iosas_precertsubmissionapprovaldate: null,
    _iosas_precertsubmissionapprover_value: null,
    iosas_interviewreviewnotes: null,
    iosas_interviewstatus1: null,
    iosas_authorityaddressline2: null,
    _iosas_interimcertificationreviewer_value: null,
    iosas_interviewadditionalinformation: null,
    _iosas_applicationsubmissionapprover_value: null,
    _iosas_precertsubmissionreviewer_value: null,
    iosas_precertreviewnotes: null,
    iosas_reviewstatus: null,
    iosas_applicationsubmissionapprovaldate: null,
    iosas_interviewreviewdate: null,
    _iosas_approver_value: null,
    iosas_detailsofinvolvement: null,
    iosas_phonenumber: null,
    iosas_precertificationstatus: null,
    _stageid_value: null,
    iosas_reviewnotes: null,
    iosas_approvaldate: null,
    _iosas_interviewapprover_value: null,
    iosas_interviewapprovaldate: null,
    iosas_schoolassociationother: null,
    iosas_acknowledgementdate: null,
    iosas_incorporationtype: null,
    iosas_hastheauthoritydevelopedarefundpolicy: null,
    iosas_completedfreetuitionrefundpolicy: false,
    iosas_cantheauthorityconfirmtestingvspolicy: false,
    iosas_feerefundpolicyconsistentwithguidelines: false,
    iosas_policysubmitted: false,

    // Group Certification - NEED CONFIRMATION
    // MISSING - group 4 fields
    iosas_familiarwithgrantstoispolicyifseekingfunds: false,
    iosas_willsaoperateonnonprofitbasis: false,

    // school Facility - DONE?
    iosas_nameofmunicipalityorregionaldistrict:
      'iosas_nameofmunicipalityorregionaldistrict',
    iosas_whatstepsareyoutakingtoacquirethefacility:
      'iosas_whatstepsareyoutakingtoacquirethefacility',
    iosas_confirmationofleadtestingfordrinkingwater: false,
    iosas_studentshousedinadormitorysetting: true,
    iosas_studentshousedinahomesetting: false,
    iosas_hastheauthoritycontactedlocalgovernment: false,

    // Scool Policies - DONE?
    iosas_anaphylaxispolicyandprocedures: false,
    iosas_appealsprocesspolicy: false,
    iosas_boardingsafetyandsupervisionpolicy: null,
    iosas_childabusepreventionpolicy: false,
    iosas_studentconductstandardsdisciplinepolicy: false,
    iosas_emergencydrillspolicyproceduresresponse: false,
    iosas_policyincludessectionsdealingwithemergencies: false,
    iosas_otheremergencydrillsimplemeneted: false,
    iosas_policyincludepermanentschoolclosure: false,
    iosas_graduationprogramcreditspolicyifapplicable: null,
    iosas_harassmentandbullyingpreventionpolicy: false,
    iosas_homeschoolingpolicyifapplicable: null,
    iosas_internationalstudentpoliciesifapplicable: null,
    iosas_complywithhomestayguidelines: null,
    iosas_willapplyforstudentgraduationcreditpolicy: null,
    iosas_privacypolicy: false,
    iosas_specialeducationpolicy: null,
    iosas_willdevelopbudgetforexpenditurebasedoniep: false,
    iosas_learningassistanceforspecialstudents: false,
    iosas_willhavecompletioncertificatepolicy: false,
    iosas_educationalresourcepolicy: false,
    iosas_testingdrinkingwaterforleadcontentpolicy: true,
    iosas_schoolclosurepolicy: false,
    iosas_studentrecordspolicy: false,
    iosas_studentsupervisionpolicies: false,
    iosas_refundpolicyconsistentwiththeguidelines: false,
    iosas_teacherandprincipalevaluationpolicy: false,
    iosas_ifnotoanyschoolpolicyexplainwhy:
      'iosas_ifnotoanyschoolpolicyexplainwhy',

    // Educational Program
    // MISSING - additional programs checklist
    iosas_describefamiliaritywithbcscurriculum:
      'iosas_describefamiliaritywithbcscurriculum',

    iosas_additionalprograms: null, // Is this an array for the checklists??
    iosas_additionalprogramsother: 'iosas_additionalprogramsother',

    // student Enrolment - DONE - GET CONFIRMATION
    iosas_numberofstudentskindergarten: 1,
    iosas_numberofstudentsg1: 2,
    iosas_numberofstudentsg2: 3,
    iosas_numberofstudentsg3: 0,
    iosas_numberofstudentsg4: 0,
    iosas_numberofstudentsg5: 0,
    iosas_numberofstudentsg6: 0,
    iosas_numberofstudentsg7: 0,
    iosas_primaryschooltotal: 6,
    iosas_numberofstudentsg8: 0,
    iosas_numberofstudentsg9: 0,
    iosas_numberofstudentsg10: 0,
    iosas_numberofstudentsg11: 0,
    iosas_numberofstudentsg12: 0,
    iosas_highschooltotal: 0,
    iosas_totalenrolment: 0,

    // school semester -
    // MISSING - 'school semester indicator type' fields
    iosas_halfdaykindergartenproposedhoursperday: 5,
    iosas_halfdaykindergartenproposedhoursperyear: 5,
    iosas_halfdaykindergartenproposeddaysinsession: 10,
    iosas_fulldaykindergartenproposedhoursperyear: 5,
    iosas_fulldaykindergartenproposeddaysinsession: 5,
    iosas_fulldaykindergartenproposedhoursperday: 3,
    iosas_grades112proposedhoursperyear: 5,
    iosas_grades112proposeddaysinsession: 5,
    iosas_grades112proposedhoursperday: 5,

    // teacher certification - DONE - GET CONFIRMATION
    iosas_numberofteachers: 'iosas_numberofteachers',
    iosas_awareofcertificationrequirements: true,
    iosas_awareoftherequirementsforcrchecks: false,

    // Submissions - DONE - GET CONFIRMATION
    iosas_completesetofpoliciesoutlinedinchecklist: false,
    iosas_businessplanincludingfinancialinformation: false,
  },
];
