apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
labels:
  project: ${PROJECT}
  service: ${SERVICE_NAME}
objects:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: ${NAME}
    spec:
      replicas: "${{REPLICAS}}"
      revisionHistoryLimit: 10
      selector:
        deploymentconfig: ${NAME}
      strategy:
        type: Rolling
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}
            from:
              kind: ImageStreamTag
              name: ${NAME}:${IMAGE_STREAM_TAG}
              namespace: ${BUILD_NAMESPACE}
          type: ImageChange
        - type: ConfigChange
      template:
        metadata:
          labels:
            deploymentconfig: ${NAME}
        spec:
          containers:
            - env:
                - name: BUILD_ID
                  value: ${BUILD_ID}
                - name: VERSION
                  value: ${VERSION}
                - name: NODE_ENV
                  value: ${NODE_ENV}
                - name: ISSUER
                  value: ${ISSUER}
                - name: API_PORT
                  value: "${PORT}"
                - name: SERVER_FRONTEND
                  value: https://${HOST_NAME}
                - name: SOAM_URL
                  value: ${SOAM_URL}
                - name: SITEMINDER_LOGOUT_ENDPOINT
                  value: https://logontest7.gov.bc.ca/clp-cgi/logoff.cgi?retnow=1&returl=
                - name: SOAM_DISCOVERY
                  valueFrom:
                    secretKeyRef:
                      key: oidc-discovery
                      name: iosas-api-creds
                - name: SOAM_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: oidc-clientId
                      name: iosas-api-creds
                - name: SOAM_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: oidc-clientSecrect
                      name: iosas-api-creds
                - name: UI_PRIVATE_KEY
                  valueFrom:
                    secretKeyRef:
                      key: private-key
                      name: iosas-ui-sec
                - name: UI_PUBLIC_KEY
                  valueFrom:
                    secretKeyRef:
                      key: certificate
                      name: iosas-ui-sec
              image: ${IMAGE_REGISTRY}/${BUILD_NAMESPACE}/${IMAGE_STREAM_TAG}
              imagePullPolicy: Always
              name: ${NAME}
              volumeMounts:
              - name: log-storage
                mountPath: /logs
              ports:
                - containerPort: "${{PORT}}"
                  protocol: TCP
                - containerPort: 443
                  protocol: TCP
              resources:
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
              readinessProbe:
                failureThreshold: 10
                httpGet:
                  path: /api/health
                  port: "${{PORT}}"
                  scheme: HTTP
                initialDelaySeconds: 40
                periodSeconds: 30
                timeoutSeconds: 30
              livenessProbe:
                failureThreshold: 10
                httpGet:
                  path: /api/health
                  port: "${{PORT}}"
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 30
                timeoutSeconds: 15
          volumes:
          - name: log-storage
            emptyDir: {}
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${NAME}
    spec:
      ports:
        - name: 80-https
          port: 80
          targetPort: ${{PORT}}
        - name: 443-https
          port: 443
          protocol: TCP 
          targetPort: 443
      selector:
        deploymentconfig: ${NAME}
      type: ClusterIP
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${NAME}
    spec:
      host: ${HOST_NAME}
      path: ${PATH}
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${NAME}
parameters:
  - name: BUILD_ID
    value: "0"
  - name: VERSION
    value: "init"
  - name: NAME
    required: true
  - name: PROJECT
    value: iosas
  - name: SERVICE_NAME
    value: api
  - name: CPU_LIMIT
    value: "0.1"
  - name: MEMORY_LIMIT
    value: "500M"
  - name: CPU_REQUEST
    value: "0.1"
  - name: MEMORY_REQUEST
    value: "500M"
  - name: REPLICAS
    value: "1"
  - name: PORT
    value: "8080"
  - name: IMAGE_STREAM_TAG
    required: true
  - name: BUILD_NAMESPACE
    required: true
  - name: IMAGE_REGISTRY
    value: image-registry.openshift-image-registry.svc:5000
  - name: HOST_NAME
    required: true
  - name: PATH
    value: "/api/"
  - name: NODE_ENV
    value: "development"
  - name: ISSUER
    value: "ecc-iosas"
  - name: FRONT_END
    value: "/"
  - name: SOAM_URL
    value: "https://soam-dev.apps.silver.devops.gov.bc.ca"
  
