apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}-redis
labels:
  project: ${PROJECT}
  service: api
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: redis
      labels:
        app: redis
    data:
      redis-readiness.sh: |
        #!/bin/sh
        response=$(timeout 3 $1 redis-cli -h $HOSTNAME -p 6379 ping)
        if [ "$response" != "PONG" ]; then
          echo "$response"
          exit 1
        fi
      redis-liveness.sh: |
        #!/bin/sh
        response=$(timeout 3 $1 redis-cli -h $HOSTNAME -p 6379 ping)
        if [ "$response" != "PONG" ] && [ "$response" != "LOADING Redis is loading the dataset in memory" ]; then
          echo "$response"
          exit 1
        fi
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: redis-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 512Mi
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
      name: redis
      labels:
        app: redis
        app.openshift.io/runtime: redis
    spec:
      strategy:
        type: Recreate
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: redis
      template:
        metadata:
          labels:
            app: redis
        spec:
          volumes:
            - name: redis-data
              persistentVolumeClaim:
                claimName: redis-data
          containers:
            - resources:
                limits:
                  memory: 512Mi
                  cpu: 150m
                requests:
                  memory: 256Mi
                  cpu: 50m
              readinessProbe:
                exec:
                  command: ["/conf/redis-rediness.sh"]
                initialDelaySeconds: 5
                timeoutSeconds: 1
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: /dev/termination-log
              name: redis
              livenessProbe:
                exec:
                  command: ["/conf/redis-liveness.sh"]
                enabled: true
                initialDelaySeconds: 20
                periodSeconds: 5
                timeoutSeconds: 1
                successThreshold: 1
                failureThreshold: 5
              securityContext:
                capabilities: {}
                privileged: false
              ports:
                - containerPort: 6379
                  protocol: TCP
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: redis-data
                  mountPath: /data
              terminationMessagePolicy: File
              image: artifacts.developer.gov.bc.ca/docker-remote/redis:7.4.6
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: redis
      name: redis
    spec:
      ports:
        - name: tcp-6379
          port: 6379
          targetPort: 6379
      selector:
        app: redis
      type: ClusterIP
parameters:
  - name: NAME
    required: true
  - name: PROJECT 
    value: iosas
