# Build and Deploy to dev env.
# Trigger with tag dev
# Connected with repo environment 'dev'
name: OpenShift Build and Deploy to Web

on:
  push:
    branches:
      - main-dev
    tags:
      - dev

env:
  CLUSTER: https://api.silver.devops.gov.bc.ca:6443
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN_OCP4 }}
  BUILD_REF: ${{ github.base_ref }}
  ENV_PREFIX: dev
  NAMESPACE_DEV: ${{ vars.NAMESPACE_DEV }}
  SOAM_CLIENT_ID_DEV: ${{ vars.SOAM_CLIENT_ID_DEV }}
  SOAM_CLIENT_SECRET_DEV: ${{ secrets.SOAM_CLIENT_SECRET_DEV }}
jobs:
  web:
    name: OpenShift Build & Deploy
    runs-on: ubuntu-latest
    concurrency: ci-build-web
    timeout-minutes: 20
    environment:
      name: dev
    env:
      CERTIFICATE: ${{ secrets.CERT }}
      CA_CERT: ${{ secrets.CA_CERT }}
      PRIVATE_KEY: ${{ secrets.PRIV_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'frontend/**'
          base: ${{ github.ref }}
      - name: Build changes
        if: steps.changes.outputs.src == 'true'
        working-directory: './tools'
        run: |
          oc login --token="$AUTH_TOKEN" --server="$CLUSTER"
          make print-status
          make build-web
      - name: Check changes on dir
        uses: dorny/paths-filter@v2
        id: changes_tools
        with:
          filters: |
            src:
              - 'frontend/**'
              - 'tools/**'
          base: ${{ github.ref }}
      - name: Deploy changes
        if: steps.changes_tools.outputs.src == 'true'
        working-directory: './tools'
        run: |
          oc login --token="$AUTH_TOKEN" --server="$CLUSTER"
          make print-status CERTIFICATE=${{ secrets.CERT }} CA_CERT=${{ secrets.CA_CERT}} PRIVATE_KEY=${{ secrets.PRIV_KEY}}
          make promote-web 
          make deploy-web
