# Build and Deploy to dev env.
# Trigger with tag dev
# Connected with repo environment 'dev'
name: OpenShift Build and Deploy to Web

on:
  push:
    branches:
      - main-dev
    tags:
      - dev

env:
  CLUSTER: https://api.silver.devops.gov.bc.ca:6443
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN_OCP4 }}
  BUILD_REF:  ${{ github.base_ref }}

jobs:
  config:
    name: Deploy Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'tools/openshift/**'
          base: ${{ github.ref}}
      - name: Apply Changes
        working-directory: './tools'
        env:
          HOST_PREFIX: dev
        if: steps.changes.outputs.src == 'true'
        run: |
          oc login --token="$SA_TOKEN" --server="$CLUSTER"
          make print-status
          make update-dc-web
  api:
    name: OpenShift Build & Deploy
    runs-on: ubuntu-latest
    concurrency: ci-build
    timeout-minutes: 20
    env:
      HOST_PREFIX: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'frontend/**'
          base: ${{ github.ref }}
      - name: Build changes
        if: steps.changes.outputs.src == 'true'
        working-directory: './tools'
        run: |
          oc login --token="$AUTH_TOKEN" --server="$CLUSTER"
          make print-status
          make build-web
          make promote-web
