# Configuring target env
name: Prmoting app to env

on:
  push:
    tags:
      - test
      - production
env:
  CLUSTER: https://api.silver.devops.gov.bc.ca:6443
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN_OCP4 }}
  BUILD_REF: ${{ github.base_ref }}
  NAMESPACE_DEV: ${{ vars.NAMESPACE_DEV }}
  NAMESPACE_TEST: ${{ vars.NAMESPACE_TEST }}
  NAMESPACE_PROD: ${{ vars.NAMESPACE_PROD }}
  SOAM_CLIENT_ID_DEV: ${{ vars.SOAM_CLIENT_ID_DEV }}
  SOAM_CLIENT_SECRET_DEV: ${{ secrets.SOAM_CLIENT_SECRET_DEV }}
  SOAM_CLIENT_ID_TEST: ${{ vars.SOAM_CLIENT_ID_TEST }}
  SOAM_CLIENT_SECRET_TEST: ${{ secrets.SOAM_CLIENT_SECRET_TEST }}
  SOAM_CLIENT_ID_PROD: ${{ vars.SOAM_CLIENT_ID_PROD }}
  SOAM_CLIENT_SECRET_PROD: ${{ secrets.SOAM_CLIENT_SECRET_PROD }}
jobs:
  api:
    name: Openshift Promote app
    runs-on: ubuntu-latest
    concurrency: ci-config-${{ inputs.oc_env_suffix }}
    timeout-minutes: 20
    steps:
      - name: Set env
        run: echo "ENV_PREFIX=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tag build and deploy application
        working-directory: './tools'
        run: |
          oc login --token="$AUTH_TOKEN" --server="$CLUSTER"
          echo Env prefix: $ENV_PREFIX
          make print-status
          make init-api-sec
          make init-api-config
          make promote-api
          make deploy-api
          make init-web
          make promote-web
          make deploy-web
